const countriesData = [
  {name:'AD',value:'+376',text:'Andorra',native:'Andorra',capital: 'Andorra la Vella'},
  {name:'AE',value:'+971',text:'United Arab Emirates',native: 'دولة الإمارات العربية المتحدة',capital: 'Abu Dhabi'},
  {name:'AF',native: 'افغانستان',value:'+93',text:'Afghanistan',capital: 'Kabul'},
  {name:'AG',native: 'Antigua and Barbuda',value:'+1268',text:'Antigua and Barbuda',capital: 'Saint John s'},
  {name:'AI',native: 'Anguilla',value:'+1264',text:'Anguilla',capital: 'The Valley'},
  {name:'AL',native: 'Shqipëria',value:'+355',text:'Albania',capital: 'Tirana'},
  {name:'AM',native: 'Հայաստան',value:'+374',text:'Armenia',capital: 'Yerevan'},
  {name:'AO',native: 'Angola',value:'+244',text:'Angola',capital: 'Luanda'},
  {name:'AQ',native: 'Antarctica',value:'+672',text:'Antarctica',capital: ''},
  {name:'AR',native: 'Argentina',value:'+54',text:'Argentina',capital: 'Buenos Aires'},
  {name:'AS',native: 'American Samoa',value:'+1684',text:'American Samoa',capital: 'Pago Pago'},
  {name:'AT',native: 'Österreich',value:'+43',text:'Austria',capital: 'Vienna'},
  {name:'AU',native: 'Australia',value:'+61',text:'Australia',capital: 'Canberra'},
  {name:'AW',native: 'Aruba',value:'+297',text:'Aruba',capital: 'Oranjestad'},
  {name:'AX', native:'Åland', value:'+358', text:'Aland', capital:'Mariehamn'},
  {name:'AZ', native:'Azərbaycan', value:'+994', text:'Azerbaijan', capital:'Baku'},
  {name:'BA', native:'Bosna i Hercegovina', value:'+387', text:'Bosnia and Herzegovina', capital:'Sarajevo'},
  {name:'BB', native:'Barbados', value:'+1246', text:'Barbados', capital:'Bridgetown'},
  {name:'BD', native:'Bangladesh', value:'+880', text:'Bangladesh', capital:'Dhaka'},
  {name:'BE', native:'België', value:'+32', text:'Belgium', capital:'Brussels'},
  {name:'BF', native:'Burkina Faso', value:'+226', text:'Burkina Faso', capital:'Ouagadougou'},
  {name:'BG', native:'България', value:'+359', text:'Bulgaria', capital:'Sofia'},
  {name:'BH', native:'البحرين', value:'+973', text:'Bahrain', capital:'Manama'},
  {name:'BI', native:'Burundi', value:'+257', text:'Burundi', capital:'Bujumbura'},
  {name:'BJ', native:'Bénin', value:'+229', text:'Benin', capital:'Porto-Novo'},
  {name:'BL', native:'Saint-Barthélemy', value:'+590', text:'Saint Barthelemy', capital:'Gustavia'},
  {name:'BM', native:'Bermuda', value:'+1441', text:'Bermuda', capital:'Hamilton'},
  {name:'BN', native:'Negara Brunei Darussalam', value:'+673', text:'Brunei', capital:'Bandar Seri Begawan'},
  {name:'BO', native:'Bolivia', value:'+591', text:'Bolivia', capital:'Sucre'},
  {name:'BQ', native:'Bonaire', value:'+5997', text:'Bonaire', capital:'Kralendijk'},
  {name:'BR', native:'Brasil', value:'+55', text:'Brazil', capital:'Brasília'},
  {name:'BS', native:'Bahamas', value:'+1242', text:'Bahamas', capital:'Nassau'},
  {name:'BT', native:'ʼbrug-yul', value:'+975', text:'Bhutan', capital:'Thimphu'},
  {name:'BV', native:'Bouvetøya', value:'+47', text:'Bouvet Island', capital:''},
  {name:'BW', native:'Botswana', value:'+267', text:'Botswana', capital:'Gaborone'},
  {name:'BY', native:'Белару́сь', value:'+375', text:'Belarus', capital:'Minsk'},
  {name:'BZ', native:'Belize', value:'+501', text:'Belize', capital:'Belmopan'},
  {name:'CA', native:'Canada', value:'+1', text:'Canada', capital:'Ottawa'},
  {name:'CC', native:'Cocos (Keeling) Islands', value:'+61', text:'Cocos (Keeling) Islands', capital:'West Island'},
  {name:'CD', native:'République démocratique du Congo', value:'+243', text:'Democratic Republic of the Congo', capital:'Kinshasa'},
  {name:'CF', native:'Ködörösêse tî Bêafrîka', value:'+236', text:'Central African Republic', capital:'Bangui'},
  {name:'CG', native:'République du Congo', value:'+242', text:'Republic of the Congo', capital:'Brazzaville'},
  {name:'CH', native:'Schweiz', value:'+41', text:'Switzerland', capital:'Bern'},
  {name:'CI', native:"Côte d'Ivoire", value:'+225', text:'Ivory Coast', capital:'Yamoussoukro'},
  {name:'CK', native:'Cook Islands', value:'+682', text:'Cook Islands', capital:'Avarua'},
  {name:'CL', native:'Chile', value:'+56', text:'Chile', capital:'Santiago'},
  {name:'CM', native:'Cameroon', value:'+237', text:'Cameroon', capital:'Yaoundé'},
  {name:'CN', native:'中国', value:'+86', text:'China', capital:'Beijing'},
  {name:'CO', native:'Colombia', value:'+57', text:'Colombia', capital:'Bogotá'},
  {name:'CR', native:'Costa Rica', value:'+506', text:'Costa Rica', capital:'San José'},
  {name:'CU', native:'Cuba', value:'+53', text:'Cuba', capital:'Havana'},
  {name:'CV', native:'Cabo Verde', value:'+238', text:'Cape Verde', capital:'Praia'},
  {name:'CW', native:'Curaçao', value:'+5999', text:'Curacao', capital:'Willemstad'},
  {name:'CX', native:'Christmas Island', value:'+61', text:'Christmas Island', capital:'Flying Fish Cove'},
  {name:'CY', native:'Κύπρος', value:'+357', text:'Cyprus', capital:'Nicosia'},
  {name:'CZ', native:'Česká republika', value:'+420', text:'Czech Republic', capital:'Prague'},
  {name:'DE', native:'Deutschland', value:'+49', text:'Germany', capital:'Berlin'},
  {name:'DJ', native:'Djibouti', value:'+253', text:'Djibouti', capital:'Djibouti'},
  {name:'DK', native:'Danmark', value:'+45', text:'Denmark', capital:'Copenhagen'},
  {name:'DM', native:'Dominica', value:'+1767', text:'Dominica', capital:'Roseau'},
  {name:'DO', native:'República Dominicana', value:'+1809', text:'Dominican Republic', capital:'Santo Domingo'},
  {name:'DZ', native:'الجزائر', value:'+213', text:'Algeria', capital:'Algiers'},
  {name:'EC', native:'Ecuador', value:'+593', text:'Ecuador', capital:'Quito'},
  {name:'EE', native:'Eesti', value:'+372', text:'Estonia', capital:'Tallinn'},
  {name:'EG', native:'مصر', value:'+20', text:'Egypt', capital:'Cairo'},
  {name:'EH', native:'الصحراء الغربية', value:'+212', text:'Western Sahara', capital:'El Aaiún'},
  {name:'ER', native:'ኤርትራ', value:'+291', text:'Eritrea', capital:'Asmara'},
  {name:'ES', native:'España', value:'+34', text:'Spain', capital:'Madrid'},
  {name:'ET', native:'ኢትዮጵያ', value:'+251', text:'Ethiopia', capital:'Addis Ababa'},
  {name:'FI', native:'Suomi', value:'+358', text:'Finland', capital:'Helsinki'},
  {name:'FJ', native:'Fiji', value:'+679', text:'Fiji', capital:'Suva'},
  {name:'FK', native:'Falkland Islands', value:'+500', text:'Falkland Islands', capital:'Stanley'},
  {name:'FM', native:'Micronesia', value:'+691', text:'Micronesia', capital:'Palikir'},
  {name:'FO', native:'Føroyar', value:'+298', text:'Faroe Islands', capital:'Tórshavn'},
  {name:'FR', native:'France', value:'+33', text:'France', capital:'Paris'},
  {name:'GA', native:'Gabon', value:'+241', text:'Gabon', capital:'Libreville'},
  {name:'GB', native:'United Kingdom', value:'+44', text:'United Kingdom', capital:'London'},
  {name:'GD', native:'Grenada', value:'+1473', text:'Grenada', capital:"St. George's"},
  {name:'GE', native:'საქართველო', value:'+995', text:'Georgia', capital:'Tbilisi'},
  {name:'GF', native:'Guyane française', value:'+594', text:'French Guiana', capital:'Cayenne'},
  {name:'GG', native:'Guernsey', value:'+44', text:'Guernsey', capital:'St. Peter Port'},
  {name:'GH', native:'Ghana', value:'+233', text:'Ghana', capital:'Accra'},
  {name:'GI', native:'Gibraltar', value:'+350', text:'Gibraltar', capital:'Gibraltar'},
  {name:'GL', native:'Kalaallit Nunaat', value:'+299', text:'Greenland', capital:'Nuuk'},
  {name:'GM', native:'Gambia', value:'+220', text:'Gambia', capital:'Banjul'},
  {name:'GN', native:'Guinée', value:'+224', text:'Guinea', capital:'Conakry'},
  {name:'GP', native:'Guadeloupe', value:'+590', text:'Guadeloupe', capital:'Basse-Terre'},
  {name:'GQ', native:'Guinea Ecuatorial', value:'+240', text:'Equatorial Guinea', capital:'Malabo'},
  {name:'GR', native:'Ελλάδα', value:'+30', text:'Greece', capital:'Athens'},
  {name:'GS', native:'South Georgia', value:'+500', text:'South Georgia and the South Sandwich Islands', capital:'King Edward Point'},
  {name:'GT', native:'Guatemala', value:'+502', text:'Guatemala', capital:'Guatemala City'},
  {name:'GU', native:'Guam', value:'+1671', text:'Guam', capital:'Hagåtña'},
  {name:'GW', native:'Guiné-Bissau', value:'+245', text:'Guinea-Bissau', capital:'Bissau'},
  {name:'GY', native:'Guyana', value:'+592', text:'Guyana', capital:'Georgetown'},
  {name:'HK', native:'香港', value:'+852', text:'Hong Kong', capital:'City of Victoria'},
  {name:'HM', native:'Heard Island and McDonald Islands', value:'+61', text:'Heard Island and McDonald Islands', capital:''},
  {name:'HN', native:'Honduras', value:'+504', text:'Honduras', capital:'Tegucigalpa'},
  {name:'HR', native:'Hrvatska', value:'+385', text:'Croatia', capital:'Zagreb'},
  {name:'HT', native:'Haïti', value:'+509', text:'Haiti', capital:'Port-au-Prince'},
  {name:'HU', native:'Magyarország', value:'+36', text:'Hungary', capital:'Budapest'},
  {name:'ID', native:'Indonesia', value:'+62', text:'Indonesia', capital:'Jakarta'},
  {name:'IE', native:'Éire', value:'+353', text:'Ireland', capital:'Dublin'},
  {name:'IL', native:'יִשְׂרָאֵל', value:'+972', text:'Israel', capital:'Jerusalem'},
  {name:'IM', native:'Isle of Man', value:'+44', text:'Isle of Man', capital:'Douglas'},
  {name:'IN', native:'भारत', value:'+91', text:'India', capital:'New Delhi'},
  {name:'IO', native:'British Indian Ocean Territory', value:'+246', text:'British Indian Ocean Territory', capital:'Diego Garcia'},
  {name:'IQ', native:'العراق', value:'+964', text:'Iraq', capital:'Baghdad'},
  {name:'IR', native:'ایران', value:'+98', text:'Iran', capital:'Tehran'},
  {name:'IS', native:'Ísland', value:'+354', text:'Iceland', capital:'Reykjavik'},
  {name:'IT', native:'Italia', value:'+39', text:'Italy', capital:'Rome'},
  {name:'JE', native:'Jersey', value:'+44', text:'Jersey', capital:'Saint Helier'},
  {name:'JM', native:'Jamaica', value:'+1876', text:'Jamaica', capital:'Kingston'},
  {name:'JO', native:'الأردن', value:'+962', text:'Jordan', capital:'Amman'},
  {name:'JP', native:'日本', value:'+81', text:'Japan', capital:'Tokyo'},
  {name:'KE', native:'Kenya', value:'+254', text:'Kenya', capital:'Nairobi'},
  {name:'KG', native:'Кыргызстан', value:'+996', text:'Kyrgyzstan', capital:'Bishkek'},
  {name:'KH', native:'Kâmpŭchéa', value:'+855', text:'Cambodia', capital:'Phnom Penh'},
  {name:'KI', native:'Kiribati', value:'+686', text:'Kiribati', capital:'South Tarawa'},
  {name:'KM', native:'Komori', value:'+269', text:'Comoros', capital:'Moroni'},
  {name:'KN', native:'Saint Kitts and Nevis', value:'+1869', text:'Saint Kitts and Nevis', capital:'Basseterre'},
  {name:'KP', native:'북한', value:'+850', text:'North Korea', capital:'Pyongyang'},
  {name:'KR', native:'대한민국', value:'+82', text:'South Korea', capital:'Seoul'},
  {name:'KW', native:'الكويت', value:'+965', text:'Kuwait', capital:'Kuwait City'},
  {name:'KY', native:'Cayman Islands', value:'+1345', text:'Cayman Islands', capital:'George Town'},
  {name:'KZ', native:'Қазақстан', value:'+7', text:'Kazakhstan', capital:'Astana'},
  {name:'LA', native:'ສປປລາວ', value:'+856', text:'Laos', capital:'Vientiane'},
  {name:'LB', native:'لبنان', value:'+961', text:'Lebanon', capital:'Beirut'},
  {name:'LC', native:'Saint Lucia', value:'+1758', text:'Saint Lucia', capital:'Castries'},
  {name:'LI', native:'Liechtenstein', value:'+423', text:'Liechtenstein', capital:'Vaduz'},
  {name:'LK', native:'śrī laṃkāva', value:'+94', text:'Sri Lanka', capital:'Colombo'},
  {name:'LR', native:'Liberia', value:'+231', text:'Liberia', capital:'Monrovia'},
  {name:'LS', native:'Lesotho', value:'+266', text:'Lesotho', capital:'Maseru'},
  {name:'LT', native:'Lietuva', value:'+370', text:'Lithuania', capital:'Vilnius'},
  {name:'LU', native:'Luxembourg', value:'+352', text:'Luxembourg', capital:'Luxembourg'},
  {name:'LV', native:'Latvija', value:'+371', text:'Latvia', capital:'Riga'},
  {name:'LY', native:'ليبيا', value:'+218', text:'Libya', capital:'Tripoli'},
  {name:'MA', native:'المغرب', value:'+212', text:'Morocco', capital:'Rabat'},
  {name:'MC', native:'Monaco', value:'+377', text:'Monaco', capital:'Monaco'},
  {name:'MD', native:'Moldova', value:'+373', text:'Moldova', capital:'Chișinău'},
  {name:'ME', native:'Црна Гора', value:'+382', text:'Montenegro', capital:'Podgorica'},
  {name:'MF', native:'Saint-Martin', value:'+590', text:'Saint Martin', capital:'Marigot'},
  {name:'MG', native:'Madagasikara', value:'+261', text:'Madagascar', capital:'Antananarivo'},
  {name:'MH', native:'M̧ajeļ', value:'+692', text:'Marshall Islands', capital:'Majuro'},
  {name:'MK', native:'Северна Македонија', value:'+389', text:'North Macedonia', capital:'Skopje'},
  {name:'ML', native:'Mali', value:'+223', text:'Mali', capital:'Bamako'},
  {name:'MM', native:'မြန်မာ', value:'+95', text:'Myanmar (Burma)', capital:'Naypyidaw'},
  {name:'MN', native:'Монгол улс', value:'+976', text:'Mongolia', capital:'Ulan Bator'},
  {name:'MO', native:'澳門', value:'+853', text:'Macao', capital:''},
  {name:'MP', native:'Northern Mariana Islands', value:'+1670', text:'Northern Mariana Islands', capital:'Saipan'},
  {name:'MQ', native:'Martinique', value:'+596', text:'Martinique', capital:'Fort-de-France'},
  {name:'MR', native:'موريتانيا', value:'+222', text:'Mauritania', capital:'Nouakchott'},
  {name:'MS', native:'Montserrat', value:'+1664', text:'Montserrat', capital:'Plymouth'},
  {name:'MT', native:'Malta', value:'+356', text:'Malta', capital:'Valletta'},
  {name:'MU', native:'Maurice', value:'+230', text:'Mauritius', capital:'Port Louis'},
  {name:'MV', native:'Maldives', value:'+960', text:'Maldives', capital:'Malé'},
  {name:'MW', native:'Malawi', value:'+265', text:'Malawi', capital:'Lilongwe'},
  {name:'MX', native:'México', value:'+52', text:'Mexico', capital:'Mexico City'},
  {name:'MY', native:'Malaysia', value:'+60', text:'Malaysia', capital:'Kuala Lumpur'},
  {name:'MZ', native:'Moçambique', value:'+258', text:'Mozambique', capital:'Maputo'},
  {name:'NA', native:'Namibia', value:'+264', text:'Namibia', capital:'Windhoek'},
  {name:'NC', native:'Nouvelle-Calédonie', value:'+687', text:'New Caledonia', capital:'Nouméa'},
  {name:'NE', native:'Niger', value:'+227', text:'Niger', capital:'Niamey'},
  {name:'NF', native:'Norfolk Island', value:'+672', text:'Norfolk Island', capital:'Kingston'},
  {name:'NG', native:'Nigeria', value:'+234', text:'Nigeria', capital:'Abuja'},
  {name:'NI', native:'Nicaragua', value:'+505', text:'Nicaragua', capital:'Managua'},
  {name:'NL', native:'Nederland', value:'+31', text:'Netherlands', capital:'Amsterdam'},
  {name:'NO', native:'Norge', value:'+47', text:'Norway', capital:'Oslo'},
  {name:'NP', native:'नेपाल', value:'+977', text:'Nepal', capital:'Kathmandu'},
  {name:'NR', native:'Nauru', value:'+674', text:'Nauru', capital:'Yaren'},
  {name:'NU', native:'Niuē', value:'+683', text:'Niue', capital:'Alofi'},
  {name:'NZ', native:'New Zealand', value:'+64', text:'New Zealand', capital:'Wellington'},
  {name:'OM', native:'عمان', value:'+968', text:'Oman', capital:'Muscat'},
  {name:'PA', native:'Panamá', value:'+507', text:'Panama', capital:'Panama City'},
  {name:'PE', native:'Perú', value:'+51', text:'Peru', capital:'Lima'},
  {name:'PF', native:'Polynésie française', value:'+689', text:'French Polynesia', capital:'Papeetē'},
  {name:'PG', native:'Papua Niugini', value:'+675', text:'Papua New Guinea', capital:'Port Moresby'},
  {name:'PH', native:'Pilipinas', value:'+63', text:'Philippines', capital:'Manila'},
  {name:'PK', native:'Pakistan', value:'+92', text:'Pakistan', capital:'Islamabad'},
  {name:'PL', native:'Polska', value:'+48', text:'Poland', capital:'Warsaw'},
  {name:'PM', native:'Saint-Pierre-et-Miquelon', value:'+508', text:'Saint Pierre and Miquelon', capital:'Saint-Pierre'},
  {name:'PN', native:'Pitcairn Islands', value:'+64', text:'Pitcairn Islands', capital:'Adamstown'},
  {name:'PR', native:'Puerto Rico', value:'+1787', text:'Puerto Rico', capital:'San Juan'},
  {name:'PS', native:'فلسطين', value:'+970', text:'Palestine', capital:'Ramallah'},
  {name:'PT', native:'Portugal', value:'+351', text:'Portugal', capital:'Lisbon'},
  {name:'PW', native:'Palau', value:'+680', text:'Palau', capital:'Ngerulmud'},
  {name:'PY', native:'Paraguay', value:'+595', text:'Paraguay', capital:'Asunción'},
  {name:'QA', native:'قطر', value:'+974', text:'Qatar', capital:'Doha'},
  {name:'RE', native:'La Réunion', value:'+262', text:'Reunion', capital:'Saint-Denis'},
  {name:'RO', native:'România', value:'+40', text:'Romania', capital:'Bucharest'},
  {name:'RS', native:'Србија', value:'+381', text:'Serbia', capital:'Belgrade'},
  {name:'RU', native:'Россия', value:'+7', text:'Russia', capital:'Moscow'},
  {name:'RW', native:'Rwanda', value:'+250', text:'Rwanda', capital:'Kigali'},
  {name:'SA', native:'العربية السعودية', value:'+966', text:'Saudi Arabia', capital:'Riyadh'},
  {name:'SB', native:'Solomon Islands', value:'+677', text:'Solomon Islands', capital:'Honiara'},
  {name:'SC', native:'Seychelles', value:'+248', text:'Seychelles', capital:'Victoria'},
  {name:'SD', native:'السودان', value:'+249', text:'Sudan', capital:'Khartoum'},
  {name:'SE', native:'Sverige', value:'+46', text:'Sweden', capital:'Stockholm'},
  {name:'SG', native:'Singapore', value:'+65', text:'Singapore', capital:'Singapore'},
  {name:'SH', native:'Saint Helena', value:'+290', text:'Saint Helena', capital:'Jamestown'},
  {name:'SI', native:'Slovenija', value:'+386', text:'Slovenia', capital:'Ljubljana'},
  {name:'SJ', native:'Svalbard og Jan Mayen', value:'+4779', text:'Svalbard and Jan Mayen', capital:'Longyearbyen'},
  {name:'SK', native:'Slovensko', value:'+421', text:'Slovakia', capital:'Bratislava'},
  {name:'SL', native:'Sierra Leone', value:'+232', text:'Sierra Leone', capital:'Freetown'},
  {name:'SM', native:'San Marino', value:'+378', text:'San Marino', capital:'City of San Marino'},
  {name:'SN', native:'Sénégal', value:'+221', text:'Senegal', capital:'Dakar'},
  {name:'SO', native:'Soomaaliya', value:'+252', text:'Somalia', capital:'Mogadishu'},
  {name:'SR', native:'Suriname', value:'+597', text:'Suriname', capital:'Paramaribo'},
  {name:'SS', native:'South Sudan', value:'+211', text:'South Sudan', capital:'Juba'},
  {name:'ST', native:'São Tomé e Príncipe', value:'+239', text:'Sao Tome and Principe', capital:'São Tomé'},
  {name:'SV', native:'El Salvador', value:'+503', text:'El Salvador', capital:'San Salvador'},
  {name:'SX', native:'Sint Maarten', value:'+1721', text:'Sint Maarten', capital:'Philipsburg'},
  {name:'SY', native:'سوريا', value:'+963', text:'Syria', capital:'Damascus'},
  {name:'SZ', native:'Eswatini', value:'+268', text:'Eswatini', capital:'Lobamba'},
  {name:'TC', native:'Turks and Caicos Islands', value:'+1649', text:'Turks and Caicos Islands', capital:'Cockburn Town'},
  {name:'TD', native:'Tchad', value:'+235', text:'Chad', capital:"N'Djamena"},
  {name:'TF', native:'Territoire des Terres australes et antarctiques fr', value:'+262', text:'French Southern Territories', capital:'Port-aux-Français'},
  {name:'TG', native:'Togo', value:'+228', text:'Togo', capital:'Lomé'},
  {name:'TH', native:'ประเทศไทย', value:'+66', text:'Thailand', capital:'Bangkok'},
  {name:'TJ', native:'Тоҷикистон', value:'+992', text:'Tajikistan', capital:'Dushanbe'},
  {name:'TK', native:'Tokelau', value:'+690', text:'Tokelau', capital:'Fakaofo'},
  {name:'TL', native:'Timor-Leste', value:'+670', text:'East Timor', capital:'Dili'},
  {name:'TM', native:'Türkmenistan', value:'+993', text:'Turkmenistan', capital:'Ashgabat'},
  {name:'TN', native:'تونس', value:'+216', text:'Tunisia', capital:'Tunis'},
  {name:'TO', native:'Tonga', value:'+676', text:'Tonga', capital:"Nuku'alofa"},
  {name:'TR', native:'Türkiye', value:'+90', text:'Turkey', capital:'Ankara'},
  {name:'TT', native:'Trinidad and Tobago', value:'+1868', text:'Trinidad and Tobago', capital:'Port of Spain'},
  {name:'TV', native:'Tuvalu', value:'+688', text:'Tuvalu', capital:'Funafuti'},
  {name:'TW', native:'臺灣', value:'+886', text:'Taiwan', capital:'Taipei'},
  {name:'TZ', native:'Tanzania', value:'+255', text:'Tanzania', capital:'Dodoma'},
  {name:'UA', native:'Україна', value:'+380', text:'Ukraine', capital:'Kyiv'},
  {name:'UG', native:'Uganda', value:'+256', text:'Uganda', capital:'Kampala'},
  {name:'UM', native:'United States Minor Outlying Islands', value:'+1', text:'U.S. Minor Outlying Islands', capital:''},
  {name:'US', native:'United States', value:'+1', text:'United States', capital:'Washington D.C.'},
  {name:'UY', native:'Uruguay', value:'+598', text:'Uruguay', capital:'Montevideo'},
  {name:'UZ', native:"O'zbekiston", value:'+998', text:'Uzbekistan', capital:'Tashkent'},
  {name:'VA', native:'Vaticano', value:'+379', text:'Vatican City', capital:'Vatican City'},
  {name:'VC', native:'Saint Vincent and the Grenadines', value:'+1784', text:'Saint Vincent and the Grenadines', capital:'Kingstown'},
  {name:'VE', native:'Venezuela', value:'+58', text:'Venezuela', capital:'Caracas'},
  {name:'VG', native:'British Virgin Islands', value:'+1284', text:'British Virgin Islands', capital:'Road Town'},
  {name:'VI', native:'United States Virgin Islands', value:'+1340', text:'U.S. Virgin Islands', capital:'Charlotte Amalie'},
  {name:'VN', native:'Việt Nam', value:'+84', text:'Vietnam', capital:'Hanoi'},
  {name:'VU', native:'Vanuatu', value:'+678', text:'Vanuatu', capital:'Port Vila'},
  {name:'WF', native:'Wallis et Futuna', value:'+681', text:'Wallis and Futuna', capital:'Mata-Utu'},
  {name:'WS', native:'Samoa', value:'+685', text:'Samoa', capital:'Apia'},
  {name:'XK', native:'Republika e Kosovës', value:'+377', text:'Kosovo', capital:'Pristina'},
  {name:'YE', native:'اليَمَن', value:'+967', text:'Yemen', capital:"Sana'a"},
  {name:'YT', native:'Mayotte', value:'+262', text:'Mayotte', capital:'Mamoudzou'},
  {name:'ZA', native:'South Africa', value:'+27', text:'South Africa', capital:'Pretoria'},
  {name:'ZM', native:'Zambia', value:'+260', text:'Zambia', capital:'Lusaka'},
  {name:'ZW', native:'Zimbabwe', value:'+263', text:'Zimbabwe', capital:'Harare'}
]
export const countriesCode = countriesData.map(country => ({
  text: country.name+' '+country.value,
  value: country.value
}));