version: "3.8"

services:
  go:
    build: ./go
    image: dnylfrd/go-mongo-vue:go-1
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - minio
    environment:
      - MONGO_URI=mongodb://db:27017
      - REDIS_ADDR=redis:6379
      - REDIS_PASS=redisPass123
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password123
      - MINIO_BUCKET=media

  vue:
    build: ./vue
    image: dnylfrd/go-mongo-vue:vue-1
    ports:
      - "3000:80"
    depends_on:
      - go
    volumes:
      - ./vue/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=goMongoVue
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: redisdb
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    volumes:
      - minio-data:/data

volumes:
  mongo-data:
  redis-data:
  minio-data:
