version: "3.8"
services:
  go:
    build: ./go
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - MONGO_URI=mongodb://db:27017
      - REDIS_ADDR=redis:6379
      # - REDIS_PASS=

  vue:
    build: ./vue
    ports:
      - "3000:80"
    depends_on:
      - go
    volumes:
      - ./vue/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=goMongoVue
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: redisdb
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
