FROM php:8.3-fpm
RUN apt-get update && apt-get install -y \
    git unzip libzip-dev zip curl libpng-dev libonig-dev libxml2-dev bash netcat-openbsd \
    && docker-php-ext-install pdo_mysql zip bcmath gd
COPY --from=composer:2.8.8 /usr/bin/composer /usr/bin/composer
WORKDIR /var/www/html
COPY . .
RUN composer install --no-interaction --optimize-autoloader && rm -rf /root/.composer/cache
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache
EXPOSE 7000
CMD php artisan serve --host=0.0.0.0 --port=7000