FROM golang:1.24-alpine
WORKDIR /app
RUN apk add --no-cache git ca-certificates curl
COPY go.mod go.sum ./
ENV GOPROXY=https://goproxy.cn,direct
RUN go mod download
COPY . .
RUN go build -o server main.go
EXPOSE 8080
CMD ["./server"]