FROM golang:1.24-alpine
WORKDIR /app
RUN apk add --no-cache git ca-certificates
COPY go/go.mod ./
COPY go/go.sum  ./
COPY modules/users/go ../modules/users/go
ENV GOPROXY=https://goproxy.cn,direct
RUN go mod download
RUN go mod tidy
COPY go/ ./
RUN go build -o server main.go
EXPOSE 8080
CMD ["./server"]